# Generated by Django 4.1.3 on 2022-12-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paxfu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='password',
        ),
    ]
