# Generated by Django 4.1.3 on 2023-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paxfu', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
            ],
        ),
    ]
