services:
  - type: web
    name: paxful-app        # 👈 change to your app name
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn paxful.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: paxful.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
